[package]
name = "kana2kanzi"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
rusqlite = { version = "0.32.0", features = ["bundled"] }
xml = "0.8.20"

[dev-dependencies]
tmpfile = "0.0.3"
